title: Ariana updates
author: Novera(a.k.a. Ariana's number 1 fan)
email: nwadu1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
So you basically already know I'm obsessed with Ariana Grande.
So this "blog" is going to basically just be updates.
I would also do updates on other celebrities like
Hayley Kiyoko and Zane Hijazi because I also love them :)
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
